env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  project: tsconfig.json
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
settings:
  react:
    version: detect
rules: 
  react/react-in-jsx-scope: 0
  "@typescript-eslint/no-confusing-void-expression": 0
  "@typescript-eslint/triple-slash-reference": 0